/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as PostIdRouteImport } from './routes/post/$id'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as MainNotificationsRouteImport } from './routes/_main/notifications'
import { Route as MainExploreRouteImport } from './routes/_main/explore'
import { Route as MainUserIdRouteImport } from './routes/_main/user/$id'
import { Route as MainCommunitiesIdRouteImport } from './routes/_main/communities/$id'
import { Route as CommunitiesIdSettingsRouteRouteImport } from './routes/communities/$id/settings/route'
import { Route as CommunitiesIdSettingsIndexRouteImport } from './routes/communities/$id/settings/index'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MainNotificationsRoute = MainNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainExploreRoute = MainExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainUserIdRoute = MainUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCommunitiesIdRoute = MainCommunitiesIdRouteImport.update({
  id: '/communities/$id',
  path: '/communities/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const CommunitiesIdSettingsRouteRoute =
  CommunitiesIdSettingsRouteRouteImport.update({
    id: '/communities/$id/settings',
    path: '/communities/$id/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunitiesIdSettingsIndexRoute =
  CommunitiesIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CommunitiesIdSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/error': typeof ErrorRoute
  '/explore': typeof MainExploreRoute
  '/notifications': typeof MainNotificationsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/post/$id': typeof PostIdRoute
  '/': typeof MainIndexRoute
  '/communities/$id/settings': typeof CommunitiesIdSettingsRouteRouteWithChildren
  '/communities/$id': typeof MainCommunitiesIdRoute
  '/user/$id': typeof MainUserIdRoute
  '/communities/$id/settings/': typeof CommunitiesIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/explore': typeof MainExploreRoute
  '/notifications': typeof MainNotificationsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/post/$id': typeof PostIdRoute
  '/': typeof MainIndexRoute
  '/communities/$id': typeof MainCommunitiesIdRoute
  '/user/$id': typeof MainUserIdRoute
  '/communities/$id/settings': typeof CommunitiesIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/_main/explore': typeof MainExploreRoute
  '/_main/notifications': typeof MainNotificationsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/post/$id': typeof PostIdRoute
  '/_main/': typeof MainIndexRoute
  '/communities/$id/settings': typeof CommunitiesIdSettingsRouteRouteWithChildren
  '/_main/communities/$id': typeof MainCommunitiesIdRoute
  '/_main/user/$id': typeof MainUserIdRoute
  '/communities/$id/settings/': typeof CommunitiesIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/error'
    | '/explore'
    | '/notifications'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/post/$id'
    | '/'
    | '/communities/$id/settings'
    | '/communities/$id'
    | '/user/$id'
    | '/communities/$id/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/explore'
    | '/notifications'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/post/$id'
    | '/'
    | '/communities/$id'
    | '/user/$id'
    | '/communities/$id/settings'
  id:
    | '__root__'
    | '/_main'
    | '/error'
    | '/_main/explore'
    | '/_main/notifications'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/post/$id'
    | '/_main/'
    | '/communities/$id/settings'
    | '/_main/communities/$id'
    | '/_main/user/$id'
    | '/communities/$id/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  PostIdRoute: typeof PostIdRoute
  CommunitiesIdSettingsRouteRoute: typeof CommunitiesIdSettingsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/notifications': {
      id: '/_main/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MainNotificationsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/explore': {
      id: '/_main/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MainExploreRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/user/$id': {
      id: '/_main/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof MainUserIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/communities/$id': {
      id: '/_main/communities/$id'
      path: '/communities/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof MainCommunitiesIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/communities/$id/settings': {
      id: '/communities/$id/settings'
      path: '/communities/$id/settings'
      fullPath: '/communities/$id/settings'
      preLoaderRoute: typeof CommunitiesIdSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$id/settings/': {
      id: '/communities/$id/settings/'
      path: '/'
      fullPath: '/communities/$id/settings/'
      preLoaderRoute: typeof CommunitiesIdSettingsIndexRouteImport
      parentRoute: typeof CommunitiesIdSettingsRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainExploreRoute: typeof MainExploreRoute
  MainNotificationsRoute: typeof MainNotificationsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainCommunitiesIdRoute: typeof MainCommunitiesIdRoute
  MainUserIdRoute: typeof MainUserIdRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainExploreRoute: MainExploreRoute,
  MainNotificationsRoute: MainNotificationsRoute,
  MainIndexRoute: MainIndexRoute,
  MainCommunitiesIdRoute: MainCommunitiesIdRoute,
  MainUserIdRoute: MainUserIdRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface CommunitiesIdSettingsRouteRouteChildren {
  CommunitiesIdSettingsIndexRoute: typeof CommunitiesIdSettingsIndexRoute
}

const CommunitiesIdSettingsRouteRouteChildren: CommunitiesIdSettingsRouteRouteChildren =
  {
    CommunitiesIdSettingsIndexRoute: CommunitiesIdSettingsIndexRoute,
  }

const CommunitiesIdSettingsRouteRouteWithChildren =
  CommunitiesIdSettingsRouteRoute._addFileChildren(
    CommunitiesIdSettingsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  PostIdRoute: PostIdRoute,
  CommunitiesIdSettingsRouteRoute: CommunitiesIdSettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
