/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunitiesCreateRouteImport } from './routes/communities/create'
import { Route as CommunitiesIdRouteImport } from './routes/communities/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCreateRoute = CommunitiesCreateRouteImport.update({
  id: '/communities/create',
  path: '/communities/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIdRoute = CommunitiesIdRouteImport.update({
  id: '/communities/$id',
  path: '/communities/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/communities/create': typeof CommunitiesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/communities/create': typeof CommunitiesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/communities/create': typeof CommunitiesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/communities/$id' | '/communities/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/communities/$id' | '/communities/create'
  id: '__root__' | '/' | '/communities/$id' | '/communities/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunitiesIdRoute: typeof CommunitiesIdRoute
  CommunitiesCreateRoute: typeof CommunitiesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/create': {
      id: '/communities/create'
      path: '/communities/create'
      fullPath: '/communities/create'
      preLoaderRoute: typeof CommunitiesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$id': {
      id: '/communities/$id'
      path: '/communities/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof CommunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunitiesIdRoute: CommunitiesIdRoute,
  CommunitiesCreateRoute: CommunitiesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
